#receivers:
#  otlp:
#    protocols:
#      grpc:
#
#processors:
#  # batch metrics before sending to reduce API usage
#  batch:
#    send_batch_max_size: 1000
#    send_batch_size: 100
#    timeout: 10s
#
#exporters:
#  otlp/tempo:
#    endpoint: "http://tempo:4317"
#    tls:
#      insecure: true
#
#service:
#  pipelines:
#    traces:
#      receivers: [otlp]
#      processors: [batch]
#      exporters: [otlp/tempo]

#receivers:
#  otlp:
#    protocols:
#      grpc:
#exporters:
#  otlp:
#    endpoint: tempo:4317
#    tls:
#      insecure: true
#service:
#  pipelines:
#    traces:
#      receivers: [otlp]
#      exporters: [otlp]

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317  # Слушаем на ВСЕХ интерфейсах
      http:
        endpoint: 0.0.0.0:4318

exporters:
  # ПРАВИЛЬНЫЙ ЭКСПОРТЕР ДЛЯ TEMPO v2.9
  otlphttp:
    endpoint: http://tempo:4318  # HTTP endpoint для Tempo
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlphttp]  # Используем HTTP экспорт