services:
  dev-psql:
    image: postgres:17-alpine
    container_name: dev-psql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notifications_db
    ports:
      - "5432:5432"
  dev-mb:
    image: rabbitmq:4-management-alpine
    container_name: dev-mb
    volumes:
      - ./message_broker/definitions.json:/etc/rabbitmq/definitions.json
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
      RABBITMQ_DEFAULT_VHOST: /
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbitmq_management load_definitions '/etc/rabbitmq/definitions.json'"
    ports:
      - "5672:5672"
      - "15672:15672"
  dev-prom:
    image: prom/prometheus:latest
    container_name: dev-prom
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
    ports:
      - "9090:9090"
  dev-alloy:
    image: grafana/alloy:latest
    container_name: dev-alloy
    user: root
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy:ro
#      надо зашарить зачем вообще и че за волюмы это. предположения есть.
#      - /var/lib/docker/containers:/var/lib/docker/containers:ro
#      - /var/run/docker.sock:/var/run/docker.sock
#      - /var/log:/var/log:ro
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:9080
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
    ports:
      - "9080:9080"
      - "4317:4317"
      - "4318:4318"
    depends_on:
      dev-tempo:
        condition: service_started
  dev-tempo:
    image: grafana/tempo:2.9.0
    container_name: dev-tempo
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo/tempo.yaml
      - tempo_data:/var/tempo
    command: [ "-config.file=/etc/tempo/tempo.yaml" ]
    ports:
      - "3200:3200"
  dev-grafana:
    image: grafana/grafana:latest
    container_name: dev-grafana
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_SECURITY_ADMIN_USER: grafana
      GF_SECURITY_ADMIN_PASSWORD: grafana
      GF_METRICS_ENABLED: "true"
    ports:
      - "3000:3000"

volumes:
  tempo_data: