"""empty message

Revision ID: 3186441d60db
Revises: 1b9ad94cbe48
Create Date: 2025-11-23 10:25:12.300174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3186441d60db'
down_revision: Union[str, Sequence[str], None] = '1b9ad94cbe48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_position_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'position_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('position_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_position_id_fkey'), 'users', 'positions', ['position_id'], ['id'])
    # ### end Alembic commands ###
