"""add stateful_tokens table

Revision ID: d56274cd1f84
Revises: f681bf350b70
Create Date: 2025-09-04 17:20:00.094987

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd56274cd1f84'
down_revision: Union[str, Sequence[str], None] = 'f681bf350b70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stateful_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stateful_tokens_id'), 'stateful_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_stateful_tokens_token'), 'stateful_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_stateful_tokens_user_id'), 'stateful_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stateful_tokens_user_id'), table_name='stateful_tokens')
    op.drop_index(op.f('ix_stateful_tokens_token'), table_name='stateful_tokens')
    op.drop_index(op.f('ix_stateful_tokens_id'), table_name='stateful_tokens')
    op.drop_table('stateful_tokens')
    # ### end Alembic commands ###
