"""init

Revision ID: d71ef1ba876f
Revises:

Create Date: 2025-09-17 14:52:30.300092

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d71ef1ba876f"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stateful_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=128), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("used", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_stateful_tokens_id"), "stateful_tokens", ["id"], unique=False)
    op.create_index(op.f("ix_stateful_tokens_token"), "stateful_tokens", ["token"], unique=True)
    op.create_index(op.f("ix_stateful_tokens_user_id"), "stateful_tokens", ["user_id"], unique=False)
    op.drop_index(op.f("ix_pvz_workers_pvz_id"), table_name="pvz_workers")
    op.drop_index(op.f("ix_pvz_workers_worker_id"), table_name="pvz_workers")
    op.drop_table("pvz_workers")
    op.drop_index(op.f("ix_pvzs_code"), table_name="pvzs")
    op.drop_index(op.f("ix_pvzs_curator_id"), table_name="pvzs")
    op.drop_index(op.f("ix_pvzs_owner_id"), table_name="pvzs")
    op.drop_table("pvzs")
    op.create_index(op.f("ix_refresh_tokens_expires_at"), "refresh_tokens", ["expires_at"], unique=False)
    op.add_column("users", sa.Column("name", sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "name")
    op.drop_index(op.f("ix_refresh_tokens_expires_at"), table_name="refresh_tokens")
    op.create_table(
        "pvzs",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('pvzs_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("code", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("city", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
        sa.Column("address", sa.VARCHAR(length=512), autoincrement=False, nullable=True),
        sa.Column("phone", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("owner_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("curator_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["curator_id"], ["users.id"], name="pvzs_curator_id_fkey"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], name="pvzs_owner_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="pvzs_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index(op.f("ix_pvzs_owner_id"), "pvzs", ["owner_id"], unique=False)
    op.create_index(op.f("ix_pvzs_curator_id"), "pvzs", ["curator_id"], unique=False)
    op.create_index(op.f("ix_pvzs_code"), "pvzs", ["code"], unique=True)
    op.create_table(
        "pvz_workers",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("pvz_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("worker_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "assigned_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["pvz_id"], ["pvzs.id"], name=op.f("pvz_workers_pvz_id_fkey")),
        sa.ForeignKeyConstraint(["worker_id"], ["users.id"], name=op.f("pvz_workers_worker_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("pvz_workers_pkey")),
    )
    op.create_index(op.f("ix_pvz_workers_worker_id"), "pvz_workers", ["worker_id"], unique=False)
    op.create_index(op.f("ix_pvz_workers_pvz_id"), "pvz_workers", ["pvz_id"], unique=False)
    op.drop_index(op.f("ix_stateful_tokens_user_id"), table_name="stateful_tokens")
    op.drop_index(op.f("ix_stateful_tokens_token"), table_name="stateful_tokens")
    op.drop_index(op.f("ix_stateful_tokens_id"), table_name="stateful_tokens")
    op.drop_table("stateful_tokens")
    # ### end Alembic commands ###
