default_language_version:
  python: python3.11

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit

    rev: v0.14.0
    hooks:
      - id: ruff-check
        args: [ --fix ]
        files: ^(auth_service|pvz_service)/.*\.(py|pyi)$

      - id: ruff-format
        files: ^(auth_service|pvz_service)/.*\.(py|pyi)$
