spring:
  docker:
    compose:
      enabled: true
      file:
        - docker_build/dev/docker-compose.yaml
  jpa:
    show-sql: true
  mail:
    host: smtp.gmail.com
    username: ${SMTP_USER}
    password: ${SMTP_PASS}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 10000
          writetimeout: 10000
  datasource:
    username: developer
    password: developer
    url: jdbc:postgresql://localhost:5432/notifications_db

logging:
  level:
    com.supvz.notifications_service: trace

# noinspection undefined
app:
  notification:
    schedule:
      cleaning:
        delay-ms: 86400000
        ttl:
          email-days: 7
          viewed-days: 7
          not-viewed-days: 30
    number-retry-attempts: 2
  websocket:
    base-topic: topic
    allowed-origins: localhost:8003
  cors:
    allowed-origins: localhost:8003
    allowed-methods: GET, POST, PUT, DELETE, OPTIONS
    allow-credentials: false
  messaging:
    inbox-queue: inbox-queue
  inbox:
    thread:
      core-pool-size: 50
      max-pool-size: 80
      queue-capacity: 120
      #     Capacity должна превышать batch-size. В два раза - дефолт.
      name-prefix: inbox-
      wait-tasks-shutdown: true
      await-termination-sec: 60
    reservation-min: 1
    cleaning-min: 3
    schedule:
      cleaning:
        batch-size: 30
        delay-ms: 3000
      processing:
        batch-size: 50
        delay-ms: 10000