spring:
  docker:
    compose:
      enabled: false
  datasource:
    username: ${DB_USER}
    password: ${DB_PASS}
    url: ${DB_URL}
  rabbitmq:
    username: ${MB_USER}
    password: ${MB_PASS}
    virtual-host: ${MB_VHOST}
    host: ${MB_HOST}
    port: ${MB_PORT}
  mail:
    host: ${SMTP_HOST}
    username: ${SMTP_USER}
    password: ${SMTP_PASS}
    port: ${SMTP_PORT}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: ${SMTP_CON_TIMEOUT}
          timeout: ${SMTP_TIMEOUT}
          writetimeout: ${SMTP_WRITE_TIMEOUT}
# noinspection undefined
app:
  notification:
    number-retry-attempts: ${NOTIFICATION_PROCESSING_NUMBER_RETRIES}
  websocket:
    base-topic: ${WEBSOCKET_BASE_TOPIC}
    allowed-origins:
      - "*"
  cors:
    allowed-origins:
      - "*"
    allowed-methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "OPTIONS"
  messaging:
    inbox-queue: ${MESSAGING_INBOX_QUEUE}
  inbox:
    reservation-min: ${INBOX_RESERVATION_IN_MINUTES}
    cleaning-min: ${INBOX_CLEANING_IN_MINUTES}
    polling:
      cleaning:
        batch-size: ${INBOX_CLEANING_BATCH_SIZE}
        delay-ms: ${INBOX_CLEANING_DELAY_IN_MS}
      processing:
        batch-size: ${INBOX_PROCESSING_BATCH_SIZE}
        delay-ms: ${INBOX_PROCESSING_DELAY_IN_MS}