#stream_over_http_enabled: true
#server:
#  http_listen_port: 3200
#  log_level: info
#
#distributor:
#  receivers:
#    otlp:
#      protocols:
#        grpc:
#          endpoint: "tempo:4317"
#
#ingester:
#  max_block_duration: 5m # cut the headblock when this much time passes. this is being set for demo purposes and should probably be left alone normally
#
#compactor:
#  compaction:
#    block_retention: 1h # overall Tempo trace retention. set for demo purposes
#
#storage:
#  trace:
#    backend: local # backend configuration to use
#    wal:
#      path: /var/tempo/wal # where to store the wal locally
#    local:
#      path: /var/tempo/blocks

server:
  http_listen_port: 3200
  grpc_listen_port: 9095  # Отдельный порт для gRPC (не для OTLP)
  log_level: info

distributor:
  receivers:
    # ПРАВИЛЬНАЯ КОНФИГУРАЦИЯ OTLP ДЛЯ TEMPO
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317  # gRPC endpoint для OTLP

ingester:
  max_block_duration: 5m

compactor:
  compaction:
    block_retention: 1h

storage:
  trace:
    backend: local
    wal:
      path: /var/tempo/wal
    local:
      path: /var/tempo/blocks