"""empty message

Revision ID: 6ea6a26e7304
Revises: 
Create Date: 2026-01-19 15:38:31.135859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ea6a26e7304'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('position_source', sa.Enum('system', 'custom', name='positionsourceenum', native_enum=False), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_employees_owner_id'), 'employees', ['owner_id'], unique=False)
    op.create_table('pvz_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('responsible_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'owner_id', name='uq_pvz_groups_name_owner')
    )
    op.create_index(op.f('ix_pvz_groups_owner_id'), 'pvz_groups', ['owner_id'], unique=False)
    op.create_index(op.f('ix_pvz_groups_responsible_id'), 'pvz_groups', ['responsible_id'], unique=False)
    op.create_table('pvzs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('type', sa.Enum('wb', 'ozon', 'yamarket', name='pvz-type', native_enum=False), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('responsible_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['pvz_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pvzs_code'), 'pvzs', ['code'], unique=True)
    op.create_index(op.f('ix_pvzs_group_id'), 'pvzs', ['group_id'], unique=False)
    op.create_index(op.f('ix_pvzs_owner_id'), 'pvzs', ['owner_id'], unique=False)
    op.create_index(op.f('ix_pvzs_responsible_id'), 'pvzs', ['responsible_id'], unique=False)
    op.create_table('employee_pvz_association',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('pvz_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pvz_id'], ['pvzs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('employee_id', 'pvz_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_pvz_association')
    op.drop_index(op.f('ix_pvzs_responsible_id'), table_name='pvzs')
    op.drop_index(op.f('ix_pvzs_owner_id'), table_name='pvzs')
    op.drop_index(op.f('ix_pvzs_group_id'), table_name='pvzs')
    op.drop_index(op.f('ix_pvzs_code'), table_name='pvzs')
    op.drop_table('pvzs')
    op.drop_index(op.f('ix_pvz_groups_responsible_id'), table_name='pvz_groups')
    op.drop_index(op.f('ix_pvz_groups_owner_id'), table_name='pvz_groups')
    op.drop_table('pvz_groups')
    op.drop_index(op.f('ix_employees_owner_id'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
