"""empty message

Revision ID: d49148f648a1
Revises: 74245fb0891a
Create Date: 2025-10-29 09:41:11.319918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd49148f648a1'
down_revision: Union[str, Sequence[str], None] = '74245fb0891a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_employees_owner_id'), 'employees', ['owner_id'], unique=False)
    op.create_index(op.f('ix_employees_phone_number'), 'employees', ['phone_number'], unique=True)
    op.create_index(op.f('ix_employees_user_id'), 'employees', ['user_id'], unique=False)
    op.create_table('employee_pvz_association',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('pvz_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pvz_id'], ['pvzs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('employee_id', 'pvz_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_pvz_association')
    op.drop_index(op.f('ix_employees_user_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_phone_number'), table_name='employees')
    op.drop_index(op.f('ix_employees_owner_id'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
