"""empty message

Revision ID: da4912f36da6
Revises: 
Create Date: 2026-01-24 09:17:32.981843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da4912f36da6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('position_source', sa.Enum('system', 'custom', name='positionsourceenum', native_enum=False), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_employees_owner_id'), 'employees', ['owner_id'], unique=False)
    op.create_table('inbox_events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.Enum('CREATE_EMPLOYEE', 'UPDATE_EMPLOYEE', 'DELETE_EMPLOYEE', 'ASSIGN_EMPLOYEE_TO_PVZ', 'UNASSIGN_EMPLOYEE_FROM_PVZ', 'CREATE_PVZ_GROUP', 'UPDATE_PVZ_GROUP', 'DELETE_PVZ_GROUP', 'ASSIGN_RESPONSIBLE_TO_PVZ_GROUP', 'CREATE_PVZ', 'UPDATE_PVZ', 'DELETE_PVZ', 'ASSIGN_PVZ_TO_GROUP', name='eventtype'), nullable=False),
    sa.Column('status', sa.Enum('PROCESSING', 'COMPLETED', 'FAILED', name='eventstatus'), server_default='PROCESSING', nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_inbox_status_created_at', 'inbox_events', ['status', 'created_at'], unique=False)
    op.create_table('pvz_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('responsible_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'owner_id', name='uq_pvz_groups_name_owner')
    )
    op.create_index(op.f('ix_pvz_groups_owner_id'), 'pvz_groups', ['owner_id'], unique=False)
    op.create_index(op.f('ix_pvz_groups_responsible_id'), 'pvz_groups', ['responsible_id'], unique=False)
    op.create_table('pvzs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('type', sa.Enum('wb', 'ozon', 'yamarket', name='pvz-type', native_enum=False), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('responsible_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['pvz_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pvzs_code'), 'pvzs', ['code'], unique=True)
    op.create_index(op.f('ix_pvzs_group_id'), 'pvzs', ['group_id'], unique=False)
    op.create_index(op.f('ix_pvzs_owner_id'), 'pvzs', ['owner_id'], unique=False)
    op.create_index(op.f('ix_pvzs_responsible_id'), 'pvzs', ['responsible_id'], unique=False)
    op.create_table('employee_pvz_association',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('pvz_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pvz_id'], ['pvzs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('employee_id', 'pvz_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_pvz_association')
    op.drop_index(op.f('ix_pvzs_responsible_id'), table_name='pvzs')
    op.drop_index(op.f('ix_pvzs_owner_id'), table_name='pvzs')
    op.drop_index(op.f('ix_pvzs_group_id'), table_name='pvzs')
    op.drop_index(op.f('ix_pvzs_code'), table_name='pvzs')
    op.drop_table('pvzs')
    op.drop_index(op.f('ix_pvz_groups_responsible_id'), table_name='pvz_groups')
    op.drop_index(op.f('ix_pvz_groups_owner_id'), table_name='pvz_groups')
    op.drop_table('pvz_groups')
    op.drop_index('ix_inbox_status_created_at', table_name='inbox_events')
    op.drop_table('inbox_events')
    op.drop_index(op.f('ix_employees_owner_id'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
