global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: notifications_service
    metrics_path: /actuator/prometheus
    static_configs:
      - labels: {}
#        так как localhost - локальная сеть внутри контейнера, поэтому прометеус на локалхосте, а сервис на 172.17.0.1.
      - targets: ["172.17.0.1:8003"]
  - job_name: notifications_db
    static_configs:
      - targets: ["dev-psql-exporter:9187"]
  - job_name: message-broker (rabbitmq)
    static_configs:
      - targets: ["dev-mb:15692"]