"""empty message

Revision ID: 7909f74fb14a
Revises: 
Create Date: 2026-02-07 15:27:59.000815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7909f74fb14a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salary_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pvz_id', sa.Integer(), nullable=False, comment='ID пункта выдачи заказов'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Название правила'),
    sa.Column('rule_type', sa.Enum('HOURLY', 'PER_SHIFT', 'FIXED', 'MIXED', name='salaryruletype'), nullable=False, comment='Тип правила расчета'),
    sa.Column('rate', sa.Float(), nullable=False, comment='Ставка (за час/смену/фиксированная)'),
    sa.Column('overtime_multiplier', sa.Float(), nullable=True, comment='Множитель за сверхурочные'),
    sa.Column('night_multiplier', sa.Float(), nullable=True, comment='Множитель за ночные часы'),
    sa.Column('holiday_multiplier', sa.Float(), nullable=True, comment='Множитель за праздничные дни'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активно ли правило'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_rules_pvz_id'), 'salary_rules', ['pvz_id'], unique=False)
    op.create_table('shift_penalties',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False, comment='ID сотрудника'),
    sa.Column('reason', sa.Text(), nullable=False, comment='Причина штрафа'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_penalties_employee_id'), 'shift_penalties', ['employee_id'], unique=False)
    op.create_table('shifts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scheduled_shift_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shifts')
    op.drop_index(op.f('ix_shift_penalties_employee_id'), table_name='shift_penalties')
    op.drop_table('shift_penalties')
    op.drop_index(op.f('ix_salary_rules_pvz_id'), table_name='salary_rules')
    op.drop_table('salary_rules')
    # ### end Alembic commands ###
