"""init

Revision ID: 94b30bc57eb2
Revises: 
Create Date: 2026-02-05 06:08:05.024015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94b30bc57eb2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_penalties',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False, comment='ID сотрудника'),
    sa.Column('reason', sa.Text(), nullable=False, comment='Причина штрафа'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_penalties_employee_id'), 'shift_penalties', ['employee_id'], unique=False)
    op.create_table('shift_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scheduled_shift_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('request_type', sa.String(length=20), nullable=False),
    sa.Column('new_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_by', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('scheduled_shift_start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_requests_scheduled_shift_id'), 'shift_requests', ['scheduled_shift_id'], unique=False)
    op.create_index(op.f('ix_shift_requests_user_id'), 'shift_requests', ['user_id'], unique=False)
    op.create_table('shifts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scheduled_shift_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shifts')
    op.drop_index(op.f('ix_shift_requests_user_id'), table_name='shift_requests')
    op.drop_index(op.f('ix_shift_requests_scheduled_shift_id'), table_name='shift_requests')
    op.drop_table('shift_requests')
    op.drop_index(op.f('ix_shift_penalties_employee_id'), table_name='shift_penalties')
    op.drop_table('shift_penalties')
    # ### end Alembic commands ###
