"""init3

Revision ID: a1bb492615b3
Revises: b2c3d4e5f6g7
Create Date: 2026-01-24 22:50:44.648626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1bb492615b3'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6g7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shift_penalties', sa.Column('employee_id', sa.Integer(), nullable=False, comment='ID сотрудника'))
    op.add_column('shift_penalties', sa.Column('reason', sa.Text(), nullable=False, comment='Причина штрафа'))
    op.drop_index(op.f('ix_shift_penalties_scheduled_shift_id'), table_name='shift_penalties')
    op.drop_index(op.f('ix_shift_penalties_type'), table_name='shift_penalties')
    op.create_index(op.f('ix_shift_penalties_employee_id'), 'shift_penalties', ['employee_id'], unique=False)
    op.drop_column('shift_penalties', 'description')
    op.drop_column('shift_penalties', 'penalty_points')
    op.drop_column('shift_penalties', 'scheduled_shift_id')
    op.drop_column('shift_penalties', 'penalty_minutes')
    op.drop_column('shift_penalties', 'detected_at')
    op.drop_column('shift_penalties', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shift_penalties', sa.Column('type', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
    op.add_column('shift_penalties', sa.Column('detected_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('shift_penalties', sa.Column('penalty_minutes', sa.INTEGER(), autoincrement=False, nullable=True, comment='Количество минут опоздания/раннего ухода'))
    op.add_column('shift_penalties', sa.Column('scheduled_shift_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('shift_penalties', sa.Column('penalty_points', sa.INTEGER(), autoincrement=False, nullable=False, comment='Штрафные баллы'))
    op.add_column('shift_penalties', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_shift_penalties_employee_id'), table_name='shift_penalties')
    op.create_index(op.f('ix_shift_penalties_type'), 'shift_penalties', ['type'], unique=False)
    op.create_index(op.f('ix_shift_penalties_scheduled_shift_id'), 'shift_penalties', ['scheduled_shift_id'], unique=False)
    op.drop_column('shift_penalties', 'reason')
    op.drop_column('shift_penalties', 'employee_id')
    # ### end Alembic commands ###
