name: CI_JAVA


on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    name: BUILD & TEST (${{ matrix.service }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service: [requests_service, notifications_service]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'
        cache: maven
        cache-dependency-path: ${{ matrix.service }}/pom.xml
        
    - name: Build with Maven
      working-directory: ${{matrix.service}}
      run: mvn -B clean package
